/**
 * Created by 奈何丶 on 2018/5/9.
 */
var myclass=[{
    "id" : "c_001",
    "c_name" : "喵喵班",
    "c_nameL" : "小班",
    "c_teacher" : "张三",
    "c_teacher1" : "张一",
    "c_student" : "小王",
    "c_address" : "一教001",
    "c_num" : "30",
    "c_March" : "2018-5-9",
    "c_timeR" : "8:00",
    "c_timeL" : "18:00",
    "c_timeX" : "18:30",
    "c_OptionTime" : "2018-5-9",
    "c_Option" : "病假",
    "c_OptionX" : "事假",
    "c_sex" : "男",
    "c_OptionY" : "调皮不上学",
    "c_OptionYL" : "感冒发烧39度",
    "c_school" : "四川大学",
    "c_OptionTimeL" : "2018-5-5",
},{
    "id" : "c_002",
    "c_name" : "丫丫班",
    "c_student" : "小王",
    "c_nameL" : "小班",
    "c_teacher" : "李四",
    "c_teacher1" : "李一",
    "c_address" : "一教002",
    "c_num" : "35",
    "c_timeR" : "8:00",
    "c_timeL" : "18:00",
    "c_timeX" : "18:30",
    "c_March" : "2018-5-9",
    "c_Option" : "事假",
    "c_OptionX" : "正常上课",
    "c_sex" : "男",
    "c_OptionY" : "",
    "c_OptionTime" : "",
    "c_school" : "四川大学",
    "c_OptionYL" : "家里有事",
    "c_OptionTimeL" : "2018-5-9",
},{
    "id" : "c_003",
    "c_name" : "臭臭班",
    "c_nameL" : "大班",
    "c_teacher" : "王二",
    "c_teacher1" : "王一",
    "c_student" : "小王",
    "c_address" : "一教003",
    "c_num" : "25",
    "c_timeR" : "8:00",
    "c_timeL" : "18:00",
    "c_timeX" : "18:30",
    "c_March" : "2018-5-9",
    "c_Option" : "正常出勤",
    "c_OptionX" : "正常上课",
    "c_sex" : "男",
    "c_OptionY" : "",
    "c_OptionTime" : "",
    "c_school" : "四川大学",
    "c_OptionYL" : "",
    "c_OptionTimeL" : "",
},{
    "id" : "c_007",
    "c_name" : "朵朵班",
    "c_student" : "赵五",
    "c_nameL" : "中班",
    "c_teacher" : "王二",
    "c_teacher1" : "赵一",
    "c_address" : "一教004",
    "c_num" : "25",
    "c_timeR" : "8:00",
    "c_timeL" : "18:00",
    "c_timeX" : "18:30",
    "c_March" : "2018-5-9",
    "c_Option" : "正常出勤",
    "c_OptionX" : "病假",
    "c_sex" : "男",
    "c_OptionTime" : "2018-5-9",
    "c_OptionTimeL" : "",
    "c_OptionY" : "感冒",
    "c_school" : "四川大学",
    "c_OptionYL" : "",
}];